### ISSUE TITLE
(Willing to pay $$) Advice on getting mipmaps working into external texture?

### ISSUE THREAD

**Issue by ngokevin** [liushijian2ideal/TextureLoader#3]
Hi!

Your plugin works well for me, I even reverse-engineered how to build it using Android Studio! Your plugin improves our application performance.

We added the glGenerateMipmaps and tried many things, but Unity does not seem to recognize it once it's in an external texture. Calling Texture2D.apply(true) crashes the application (in VR for us). Using normal Texture2Ds, mipmaps work for us.

We'd be to willing to pay for help, or buy some beers, or whatever, @catoxliu! Thank you.

- Kevin

**Comment by catoxliu** [comment]
Hello Kevin,

It's really great to know that this plugin helps your app.
I can't really tell anything from your description, do you check the crash stack if there is any useful info? 
I'd love to help (no charges:). but this plugin is ages and Unity changes a lot nowadays, I'm not capable offering any solutions without debugging it.

Cheers

**Comment by ngokevin** [comment]
Thanks, Shijian! There's not any useful information from the stack trace. 

Just wondering if you knew anything related to getting the mipmaps working after using `Texture2D.CreateExternalTexture`. We're not sure whether Unity knows about the mipmaps, or whether we need to call tex.Apply.

I can create a simple debuggable example if you're willing to try, or if there's any information can help you debug.

**Comment by catoxliu** [comment]
Mipmap is quite normal IMO, even though I didn't use it with external texture before (also, I don't know there is any problem to prevent you doing so).
And yes please, a simple example will be really helpful.

**Comment by ngokevin** [comment]
Okay, I will try again maybe with normal Texture2D object, and if it doesn't work, I will send you a simple example in maybe 12 hours (after I wake up). Thank you!

**Comment by ngokevin** [comment]
Hey, thanks for helping! I was able to get mipmaps working. I switched to GLES30 just in case, called texStorage2D just in case, and then made sure to set all the tex parameters again after calling glGenerateMipMaps on every texture update.

By the way, how much does your new branch with direct CPU writes improve performance over master? We are loading images around 3000x2000 but they could be bigger.

**Comment by catoxliu** [comment]
Cool, great to know it works for you.

> how much does your new branch with direct CPU writes improve performance over master

You mean by using `EXT_texture_buffer`? I didn't measure that, in my understanding, the improvement is achieved by 1. no overhead of data transfer from cpu to gpu. 2. less usage of memory. It could varies on different platforms. BTW, "Buffer textures do not support mipmapping, texture lookups with normalized floating-point texture coordinates, and texture filtering of any sort." And "only samplerBuffer (not sampler2D) could be used for Buffer Texture."

And for the master branch, the main performance issue I want to address in this plugin is that "Unity's LoadImage will cause intolerable latency due to generating new GPU resources (Texture2D)" (at least it's the problem back in 2016). So no matter how big the image is, the performance gain should be the same (get rid of creating new Texture2D). (data transfer from cpu to gpu is the same and it increases with the image size, and if you want to reduce this time, then using `EXT_texture_buffer` with its limitations).

**Comment by ngokevin** [comment]
Okay, thanks! That performance issue is perfectly addressed for us. No more hitches on image loading. Maybe doing texSubImage2D over multiple frames can help with bigger images?

Also did you use to work VR/AR at Tencent? That sounds cool. We've been interested in talking to Chinese companies doing VR!

**Comment by catoxliu** [comment]
> Maybe doing texSubImage2D over multiple frames can help with bigger images?

Yeah, could be, can't really give any advice without knowing what's this big image is used for.

> did you use to work VR/AR at Tencent?

Used to, we were developing a PC VR back then, but the product didn't go to production. Left there at early 2019 and came to NZ. Still keep my eye on VR at spare time and happy to see the industry is growing steadily. What you guys have done in A Frame is really impressive, great job!

**Comment by ngokevin** [comment]
No problem, we'll figure it out! We are just displaying very high resolution photos in VR in OVROverlay. And thanks, we are still working hard on A-Frame!

Maybe I can ask another favor if you know people working VR industry at Tencent or anywhere else? We are just interested in talking to Chinese companies to learn more what people are doing, we'd love an introduction to people! We have an idea on a VR project that I can tell you about, and we could use some help from over there. I can give you my email and my Wechat, my email is kevin@supermedium.com and my Wechat ID is `ngokevin`, if that is okay.
